const players = [
  // ATL — Dream
  { id: 70, name: "Rhyne Howard", team: "ATL", position: "G", number: "10", age: 26, height: "6'2\"", conf: "East", previousTeams: [] },
  { id: 120, name: "Naz Hillmon", team: "ATL", position: "F", number: "00", age: 26, height: "6'2\"", conf: "East", previousTeams: [] },
  { id: 121, name: "Te-Hina Paopao", team: "ATL", position: "G", number: "2", age: 23, height: "5'9\"", conf: "East", previousTeams: [] },
  { id: 122, name: "Jordin Canada", team: "ATL", position: "G", number: "3", age: 30, height: "5'6\"", conf: "East", previousTeams: ["SEA","LAS"] },
  { id: 2001, name: "Angel Reese", team: "ATL", position: "F", number: "5", age: 24, height: "6'4\"", conf: "East", previousTeams: ["CHI"] },
  { id: 2002, name: "Madina Okot", team: "ATL", position: "C", number: "11", age: 22, height: "6'6\"", conf: "East", previousTeams: [] },
  { id: 125, name: "Allisha Gray", team: "ATL", position: "G", number: "15", age: 31, height: "6'0\"", conf: "East", previousTeams: ["DAL"] },
  { id: 2003, name: "Isobel Borlase", team: "ATL", position: "G", number: "20", age: 21, height: "5'11\"", conf: "East", previousTeams: [] },
  { id: 2004, name: "Indya Nivar", team: "ATL", position: "G", number: "21", age: 23, height: "5'10\"", conf: "East", previousTeams: [] },
  { id: 2005, name: "Sika Kone", team: "ATL", position: "F", number: "23", age: 23, height: "6'3\"", conf: "East", previousTeams: ["CHI"] },
  { id: 2006, name: "Aaliyah Nye", team: "ATL", position: "G-F", number: "32", age: 23, height: "6'0\"", conf: "East", previousTeams: ["LVA"] },
  { id: 126, name: "Brionna Jones", team: "ATL", position: "F", number: "42", age: 30, height: "6'3\"", conf: "East", previousTeams: ["CON"] },
  { id: 2007, name: "Amy Okonkwo", team: "ATL", position: "F", number: "0", age: 29, height: "6'2\"", conf: "East", previousTeams: [] },

  // CHI — Sky
  { id: 97, name: "Jacy Sheldon", team: "CHI", position: "G", number: "0", age: 25, height: "5'10\"", conf: "East", previousTeams: ["DAL","CON","WAS"] },
  { id: 31, name: "Elizabeth Williams", team: "CHI", position: "C-F", number: "1", age: 32, height: "6'3\"", conf: "East", previousTeams: ["CON","ATL"] },
  { id: 76, name: "Skylar Diggins", team: "CHI", position: "G", number: "4", age: 35, height: "5'9\"", conf: "East", previousTeams: ["DAL","PHX","SEA"] },
  { id: 69, name: "Rickea Jackson", team: "CHI", position: "F", number: "5", age: 25, height: "6'2\"", conf: "East", previousTeams: ["LAS"] },
  { id: 27, name: "DiJonai Carrington", team: "CHI", position: "G-F", number: "7", age: 28, height: "5'11\"", conf: "East", previousTeams: ["CON","DAL","MIN"] },
  { id: 145, name: "Natasha Cloud", team: "CHI", position: "G", number: "9", age: 34, height: "5'10\"", conf: "East", previousTeams: ["WAS","PHX","NYL"] },
  { id: 44, name: "Kamilla Cardoso", team: "CHI", position: "C", number: "10", age: 25, height: "6'7\"", conf: "East", previousTeams: [] },
  { id: 2008, name: "Gabriela Jaquez", team: "CHI", position: "G", number: "11", age: 22, height: "6'0\"", conf: "East", previousTeams: [] },
  { id: 2009, name: "Sydney Taylor", team: "CHI", position: "G", number: "12", age: 24, height: "5'9\"", conf: "East", previousTeams: [] },
  { id: 54, name: "Maddy Westbeld", team: "CHI", position: "F", number: "21", age: 23, height: "6'3\"", conf: "East", previousTeams: [] },
  { id: 5002, name: "Courtney Vandersloot", team: "CHI", position: "G", number: "22", age: 37, height: "5'8\"", conf: "East", previousTeams: ["NYL"] },
  { id: 67, name: "Rachel Banham", team: "CHI", position: "G", number: "24", age: 32, height: "5'10\"", conf: "East", previousTeams: ["MIN","CON"] },
  { id: 12, name: "Azura Stevens", team: "CHI", position: "F-C", number: "30", age: 30, height: "6'6\"", conf: "East", previousTeams: ["DAL","LAS"] },
  { id: 2010, name: "Aicha Coulibaly", team: "CHI", position: "G", number: "35", age: 24, height: "6'0\"", conf: "East", previousTeams: [] },

  // CON — Sun
  { id: 28, name: "Diamond Miller", team: "CON", position: "F", number: "1", age: 25, height: "6'1\"", conf: "East", previousTeams: ["MIN","DAL"] },
  { id: 35, name: "Hailey Van Lith", team: "CON", position: "G", number: "2", age: 24, height: "5'9\"", conf: "East", previousTeams: ["CHI"] },
  { id: 2011, name: "Ashlon Jackson", team: "CON", position: "G", number: "3", age: 22, height: "6'0\"", conf: "East", previousTeams: [] },
  { id: 2012, name: "Charlisse Leger-Walker", team: "CON", position: "G", number: "4", age: 24, height: "5'10\"", conf: "East", previousTeams: [] },
  { id: 2013, name: "Gianna Kneepkens", team: "CON", position: "G", number: "5", age: 23, height: "5'11\"", conf: "East", previousTeams: [] },
  { id: 84, name: "Aaliyah Edwards", team: "CON", position: "F", number: "8", age: 23, height: "6'3\"", conf: "East", previousTeams: ["WAS"] },
  { id: 99, name: "Olivia Nelson-Ododa", team: "CON", position: "C", number: "10", age: 25, height: "6'5\"", conf: "East", previousTeams: ["LAS"] },
  { id: 2014, name: "Shey Peddy", team: "CON", position: "G", number: "11", age: 37, height: "5'7\"", conf: "East", previousTeams: ["WAS","PHX"] },
  { id: 2015, name: "Raegan Beers", team: "CON", position: "F", number: "15", age: 23, height: "6'4\"", conf: "East", previousTeams: [] },
  { id: 104, name: "Saniya Rivers", team: "CON", position: "G", number: "22", age: 23, height: "6'1\"", conf: "East", previousTeams: [] },
  { id: 106, name: "Aneesah Morrow", team: "CON", position: "F", number: "24", age: 23, height: "6'1\"", conf: "East", previousTeams: [] },
  { id: 147, name: "Kennedy Burke", team: "CON", position: "G-F", number: "25", age: 29, height: "6'1\"", conf: "East", previousTeams: ["IND","SEA","WAS","NYL"] },
  { id: 2016, name: "Nell Angloma", team: "CON", position: "F", number: "33", age: 20, height: "6'1\"", conf: "East", previousTeams: [] },
  { id: 129, name: "Brittney Griner", team: "CON", position: "C", number: "42", age: 35, height: "6'9\"", conf: "East", previousTeams: ["PHX","ATL"] },
  { id: 108, name: "Leila Lacan", team: "CON", position: "G", number: "47", age: 21, height: "5'11\"", conf: "East", previousTeams: [] },

  // DAL — Wings
  { id: 2017, name: "Odyssey Sims", team: "DAL", position: "G", number: "1", age: 33, height: "5'8\"", conf: "West", previousTeams: ["PHX","ATL","MIN","CON"] },
  { id: 65, name: "Paige Bueckers", team: "DAL", position: "G", number: "5", age: 24, height: "6'0\"", conf: "West", previousTeams: [] },
  { id: 2018, name: "Costanza Verona", team: "DAL", position: "G", number: "6", age: 26, height: "5'6\"", conf: "West", previousTeams: [] },
  { id: 7777, name: "Alysha Clark", team: "DAL", position: "F", number: "7", age: 38, height: "5'11\"", conf: "West", previousTeams: ["SEA","WAS","LVA"] },
  { id: 5, name: "Alanna Smith", team: "DAL", position: "F", number: "8", age: 29, height: "6'4\"", conf: "West", previousTeams: ["PHX","IND","CHI","MIN"] },
  { id: 134, name: "Aziaha James", team: "DAL", position: "G", number: "10", age: 23, height: "5'10\"", conf: "West", previousTeams: [] },
  { id: 135, name: "JJ Quinerly", team: "DAL", position: "G", number: "11", age: 23, height: "5'8\"", conf: "West", previousTeams: [] },
  { id: 2019, name: "Dulcy Fankam Mendjiadeu", team: "DAL", position: "F-C", number: "12", age: 26, height: "6'3\"", conf: "West", previousTeams: ["SEA"] },
  { id: 138, name: "Maddy Siegrist", team: "DAL", position: "F", number: "20", age: 25, height: "6'2\"", conf: "West", previousTeams: [] },
  { id: 11, name: "Arike Ogunbowale", team: "DAL", position: "G", number: "24", age: 29, height: "5'8\"", conf: "West", previousTeams: [] },
  { id: 9002, name: "Li Yueru", team: "DAL", position: "C", number: "28", age: 27, height: "6'7\"", conf: "West", previousTeams: ["CHI","SEA"] },
  { id: 95, name: "Jessica Shepard", team: "DAL", position: "F", number: "32", age: 29, height: "6'4\"", conf: "West", previousTeams: ["MIN"] },
  { id: 2020, name: "Awak Kuier", team: "DAL", position: "F", number: "34", age: 24, height: "6'6\"", conf: "West", previousTeams: [] },
  { id: 2021, name: "Azzi Fudd", team: "DAL", position: "G", number: "35", age: 23, height: "5'11\"", conf: "West", previousTeams: [] },

  // GSV — Valkyries
  { id: 34, name: "Gabby Williams", team: "GSV", position: "F", number: "1", age: 29, height: "5'11\"", conf: "West", previousTeams: ["CHI","SEA"] },
  { id: 5007, name: "Kaitlyn Chen", team: "GSV", position: "G", number: "2", age: 24, height: "5'9\"", conf: "West", previousTeams: [] },
  { id: 5008, name: "Laeticia Amihere", team: "GSV", position: "F", number: "3", age: 24, height: "6'3\"", conf: "West", previousTeams: ["ATL"] },
  { id: 2022, name: "Juste Jocyte", team: "GSV", position: "G-F", number: "4", age: 20, height: "6'0\"", conf: "West", previousTeams: [] },
  { id: 109, name: "Kayla Thornton", team: "GSV", position: "F", number: "5", age: 33, height: "6'1\"", conf: "West", previousTeams: ["WAS","DAL","NYL"] },
  { id: 132, name: "Kaila Charles", team: "GSV", position: "G-F", number: "6", age: 28, height: "6'1\"", conf: "West", previousTeams: ["CON","ATL","SEA"] },
  { id: 2023, name: "Miela Sowah", team: "GSV", position: "G", number: "7", age: 22, height: "5'10\"", conf: "West", previousTeams: [] },
  { id: 2024, name: "Ashten Prechtel", team: "GSV", position: "F", number: "11", age: 26, height: "6'5\"", conf: "West", previousTeams: [] },
  { id: 5009, name: "Iliana Rupert", team: "GSV", position: "C", number: "12", age: 24, height: "6'4\"", conf: "West", previousTeams: ["LVA"] },
  { id: 111, name: "Janelle Salaun", team: "GSV", position: "F", number: "13", age: 24, height: "6'2\"", conf: "West", previousTeams: [] },
  { id: 79, name: "Tiffany Hayes", team: "GSV", position: "G", number: "15", age: 36, height: "5'10\"", conf: "West", previousTeams: ["ATL","CON","LVA"] },
  { id: 115, name: "Veronica Burton", team: "GSV", position: "G", number: "22", age: 25, height: "5'9\"", conf: "West", previousTeams: ["DAL","CON"] },
  { id: 116, name: "Cecilia Zandalasini", team: "GSV", position: "F", number: "24", age: 30, height: "6'2\"", conf: "West", previousTeams: ["MIN"] },
  { id: 2025, name: "Ndjakalenga Mwenentanda", team: "GSV", position: "G", number: "32", age: 24, height: "6'2\"", conf: "West", previousTeams: [] },
  { id: 48, name: "Kiah Stokes", team: "GSV", position: "C", number: "41", age: 33, height: "6'3\"", conf: "West", previousTeams: ["NYL","LVA"] },

  // IND — Fever
  { id: 46, name: "Kelsey Mitchell", team: "IND", position: "G", number: "0", age: 30, height: "5'8\"", conf: "East", previousTeams: [] },
  { id: 131, name: "Myisha Hines-Allen", team: "IND", position: "F", number: "2", age: 29, height: "6'2\"", conf: "East", previousTeams: ["WAS","MIN","DAL"] },
  { id: 2026, name: "Raven Johnson", team: "IND", position: "G", number: "3", age: 22, height: "5'8\"", conf: "East", previousTeams: [] },
  { id: 6, name: "Aliyah Boston", team: "IND", position: "C-F", number: "7", age: 24, height: "6'5\"", conf: "East", previousTeams: [] },
  { id: 77, name: "Sophie Cunningham", team: "IND", position: "G", number: "8", age: 29, height: "6'1\"", conf: "East", previousTeams: ["PHX"] },
  { id: 53, name: "Lexie Hull", team: "IND", position: "G", number: "10", age: 26, height: "6'2\"", conf: "East", previousTeams: [] },
  { id: 24, name: "Damiris Dantas", team: "IND", position: "C-F", number: "12", age: 33, height: "6'4\"", conf: "East", previousTeams: ["MIN","ATL"] },
  { id: 2027, name: "Justine Pissott", team: "IND", position: "G-F", number: "13", age: 22, height: "6'4\"", conf: "East", previousTeams: [] },
  { id: 8, name: "Makayla Timpson", team: "IND", position: "F-C", number: "21", age: 23, height: "6'2\"", conf: "East", previousTeams: [] },
  { id: 16, name: "Caitlin Clark", team: "IND", position: "G", number: "22", age: 24, height: "6'0\"", conf: "East", previousTeams: [] },
  { id: 2028, name: "Bree Hall", team: "IND", position: "G", number: "23", age: 23, height: "6'1\"", conf: "East", previousTeams: [] },
  { id: 117, name: "Monique Billings", team: "IND", position: "F", number: "25", age: 30, height: "6'4\"", conf: "East", previousTeams: ["ATL","DAL","PHX","GSV"] },
  { id: 127, name: "Shatori Walker-Kimbrough", team: "IND", position: "G", number: "32", age: 29, height: "5'9\"", conf: "East", previousTeams: ["WAS","PHX","CON","ATL"] },
  { id: 140, name: "Tyasha Harris", team: "IND", position: "G", number: "52", age: 28, height: "5'10\"", conf: "East", previousTeams: ["DAL","CON"] },

  // LAS — Sparks
  { id: 2029, name: "Ta'Niya Latson", team: "LAS", position: "G", number: "0", age: 22, height: "5'8\"", conf: "West", previousTeams: [] },
  { id: 2030, name: "Chance Gray", team: "LAS", position: "G", number: "2", age: 23, height: "5'9\"", conf: "West", previousTeams: [] },
  { id: 2031, name: "Laura Ziegler", team: "LAS", position: "F", number: "4", age: 23, height: "6'2\"", conf: "West", previousTeams: [] },
  { id: 25, name: "Dearica Hamby", team: "LAS", position: "F", number: "5", age: 32, height: "6'3\"", conf: "West", previousTeams: ["LVA"] },
  { id: 2032, name: "Jihyun Park", team: "LAS", position: "G", number: "6", age: 26, height: "6'1\"", conf: "West", previousTeams: [] },
  { id: 10, name: "Ariel Atkins", team: "LAS", position: "G", number: "7", age: 29, height: "5'10\"", conf: "West", previousTeams: ["WAS","CHI"] },
  { id: 47, name: "Kelsey Plum", team: "LAS", position: "G", number: "10", age: 31, height: "5'8\"", conf: "West", previousTeams: ["LVA"] },
  { id: 66, name: "Rae Burrell", team: "LAS", position: "G-F", number: "12", age: 25, height: "6'2\"", conf: "West", previousTeams: [] },
  { id: 8001, name: "Erica Wheeler", team: "LAS", position: "G", number: "17", age: 35, height: "5'7\"", conf: "West", previousTeams: ["ATL","NYL","IND","SEA"] },
  { id: 114, name: "Kate Martin", team: "LAS", position: "G", number: "20", age: 25, height: "6'0\"", conf: "West", previousTeams: ["LVA","GSV"] },
  { id: 72, name: "Sania Feagin", team: "LAS", position: "F", number: "20", age: 23, height: "6'3\"", conf: "West", previousTeams: [] },
  { id: 17, name: "Cameron Brink", team: "LAS", position: "F", number: "22", age: 24, height: "6'4\"", conf: "West", previousTeams: [] },
  { id: 63, name: "Nneka Ogwumike", team: "LAS", position: "F", number: "30", age: 35, height: "6'2\"", conf: "West", previousTeams: ["SEA"] },
  { id: 32, name: "Emma Cannon", team: "LAS", position: "F", number: "32", age: 36, height: "6'2\"", conf: "West", previousTeams: ["PHX","IND","CON"] },

  // LVA — Aces
  { id: 37, name: "Jackie Young", team: "LVA", position: "G", number: "0", age: 28, height: "6'0\"", conf: "West", previousTeams: [] },
  { id: 49, name: "Kierstan Bell", team: "LVA", position: "F", number: "1", age: 26, height: "6'1\"", conf: "West", previousTeams: [] },
  { id: 2033, name: "Janiah Barker", team: "LVA", position: "F", number: "2", age: 22, height: "6'4\"", conf: "West", previousTeams: [] },
  { id: 130, name: "NaLyssa Smith", team: "LVA", position: "F", number: "3", age: 25, height: "6'4\"", conf: "West", previousTeams: ["IND","DAL"] },
  { id: 5012, name: "Stephanie Talbot", team: "LVA", position: "F", number: "7", age: 31, height: "6'2\"", conf: "West", previousTeams: ["PHX","MIN","SEA","LAS","GSV","NYL"] },
  { id: 23, name: "Dana Evans", team: "LVA", position: "G", number: "11", age: 27, height: "5'6\"", conf: "West", previousTeams: ["CHI"] },
  { id: 18, name: "Chelsea Gray", team: "LVA", position: "G", number: "12", age: 33, height: "5'11\"", conf: "West", previousTeams: ["LAS","CON"] },
  { id: 14, name: "Brianna Turner", team: "LVA", position: "F-C", number: "21", age: 29, height: "6'3\"", conf: "West", previousTeams: ["PHX","CHI","IND"] },
  { id: 1, name: "A'ja Wilson", team: "LVA", position: "C", number: "22", age: 29, height: "6'4\"", conf: "West", previousTeams: [] },
  { id: 2034, name: "Chennedy Carter", team: "LVA", position: "G", number: "23", age: 27, height: "5'9\"", conf: "West", previousTeams: ["ATL","LAS","CHI"] },
  { id: 39, name: "Jewell Loyd", team: "LVA", position: "G", number: "24", age: 32, height: "5'11\"", conf: "West", previousTeams: ["SEA"] },
  { id: 19, name: "Cheyenne Parker-Tyus", team: "LVA", position: "F", number: "32", age: 33, height: "6'4\"", conf: "West", previousTeams: ["CHI","ATL"] },

  // MIN — Lynx
  { id: 60, name: "Natasha Howard", team: "MIN", position: "F", number: "1", age: 34, height: "6'2\"", conf: "West", previousTeams: ["MIN","SEA","NYL","DAL","IND"] },
  { id: 2035, name: "Liatu King", team: "MIN", position: "F", number: "2", age: 24, height: "5'11\"", conf: "West", previousTeams: [] },
  { id: 128, name: "Maya Caldwell", team: "MIN", position: "G", number: "3", age: 27, height: "5'11\"", conf: "West", previousTeams: ["ATL","IND"] },
  { id: 2036, name: "Olivia Miles", team: "MIN", position: "G", number: "5", age: 23, height: "5'10\"", conf: "West", previousTeams: [] },
  { id: 92, name: "Anastasiia Olairi Kosu", team: "MIN", position: "F", number: "7", age: 21, height: "6'1\"", conf: "West", previousTeams: [] },
  { id: 2037, name: "Antonia Delaere", team: "MIN", position: "G", number: "8", age: 31, height: "5'11\"", conf: "West", previousTeams: [] },
  { id: 20, name: "Courtney Williams", team: "MIN", position: "G", number: "10", age: 32, height: "5'8\"", conf: "West", previousTeams: ["ATL","CON"] },
  { id: 2038, name: "Eliska Hamzova", team: "MIN", position: "G", number: "11", age: 25, height: "6'0\"", conf: "West", previousTeams: [] },
  { id: 124, name: "Nia Coffey", team: "MIN", position: "F", number: "12", age: 30, height: "6'1\"", conf: "West", previousTeams: ["LVA","PHX","LAS","ATL"] },
  { id: 2039, name: "Dorka Juhasz", team: "MIN", position: "F", number: "14", age: 26, height: "6'5\"", conf: "West", previousTeams: [] },
  { id: 45, name: "Kayla McBride", team: "MIN", position: "G", number: "21", age: 33, height: "5'11\"", conf: "West", previousTeams: ["LVA"] },
  { id: 2040, name: "Emma Cechova", team: "MIN", position: "C", number: "22", age: 21, height: "6'4\"", conf: "West", previousTeams: [] },
  { id: 59, name: "Napheesa Collier", team: "MIN", position: "F", number: "24", age: 29, height: "6'1\"", conf: "West", previousTeams: [] },
  { id: 2041, name: "Emese Hof", team: "MIN", position: "C", number: "25", age: 29, height: "6'3\"", conf: "West", previousTeams: [] },

  // NYL — Liberty
  { id: 74, name: "Satou Sabally", team: "NYL", position: "F", number: "0", age: 28, height: "6'4\"", conf: "East", previousTeams: ["DAL","PHX"] },
  { id: 2042, name: "Marine Fauthoux", team: "NYL", position: "G", number: "4", age: 25, height: "5'9\"", conf: "East", previousTeams: [] },
  { id: 143, name: "Rebekah Gardner", team: "NYL", position: "G", number: "7", age: 35, height: "6'1\"", conf: "East", previousTeams: ["CHI"] },
  { id: 68, name: "Rebecca Allen", team: "NYL", position: "F-G", number: "9", age: 33, height: "6'2\"", conf: "East", previousTeams: ["CON","CHI"] },
  { id: 146, name: "Leonie Fiebich", team: "NYL", position: "F", number: "13", age: 26, height: "6'4\"", conf: "East", previousTeams: [] },
  { id: 2043, name: "Raquel Carrera", team: "NYL", position: "C", number: "14", age: 24, height: "6'3\"", conf: "East", previousTeams: [] },
  { id: 2044, name: "Pauline Astier", team: "NYL", position: "G", number: "18", age: 24, height: "5'11\"", conf: "East", previousTeams: [] },
  { id: 71, name: "Sabrina Ionescu", team: "NYL", position: "G", number: "20", age: 28, height: "5'11\"", conf: "East", previousTeams: [] },
  { id: 2045, name: "Han Xu", team: "NYL", position: "C", number: "21", age: 26, height: "6'11\"", conf: "East", previousTeams: [] },
  { id: 2046, name: "Aubrey Griffin", team: "NYL", position: "G-F", number: "22", age: 24, height: "6'1\"", conf: "East", previousTeams: [] },
  { id: 148, name: "Marine Johannes", team: "NYL", position: "G", number: "23", age: 31, height: "5'10\"", conf: "East", previousTeams: [] },
  { id: 13, name: "Breanna Stewart", team: "NYL", position: "F", number: "30", age: 31, height: "6'4\"", conf: "East", previousTeams: ["SEA"] },
  { id: 40, name: "Jonquel Jones", team: "NYL", position: "C", number: "35", age: 32, height: "6'6\"", conf: "East", previousTeams: ["CON"] },
  { id: 2047, name: "Betnijah Laney-Hamilton", team: "NYL", position: "G-F", number: "44", age: 32, height: "6'0\"", conf: "East", previousTeams: ["CHI","CON","ATL"] },
  { id: 119, name: "Julie Vanloo", team: "NYL", position: "G", number: "53", age: 33, height: "5'8\"", conf: "East", previousTeams: ["WAS","GSV","LAS"] },

  // PHX — Mercury
  { id: 2048, name: "Noemie Brochant", team: "PHX", position: "F-G", number: "1", age: 23, height: "5'11\"", conf: "West", previousTeams: [] },
  { id: 43, name: "Kahleah Copper", team: "PHX", position: "G-F", number: "2", age: 31, height: "6'1\"", conf: "West", previousTeams: ["CHI"] },
  { id: 4, name: "Natasha Mack", team: "PHX", position: "F-C", number: "4", age: 28, height: "6'3\"", conf: "West", previousTeams: ["CHI","MIN"] },
  { id: 2049, name: "Shay Ciezki", team: "PHX", position: "G", number: "5", age: 22, height: "5'7\"", conf: "West", previousTeams: [] },
  { id: 2050, name: "Monique Akoa Makani", team: "PHX", position: "G", number: "8", age: 22, height: "5'10\"", conf: "West", previousTeams: [] },
  { id: 2051, name: "Valeriane Ayayi", team: "PHX", position: "F", number: "11", age: 32, height: "6'1\"", conf: "West", previousTeams: [] },
  { id: 2052, name: "Quionche Carter", team: "PHX", position: "F", number: "20", age: 23, height: "5'11\"", conf: "West", previousTeams: [] },
  { id: 2053, name: "Kiana Williams", team: "PHX", position: "G", number: "23", age: 27, height: "5'8\"", conf: "West", previousTeams: ["SEA"] },
  { id: 26, name: "DeWanna Bonner", team: "PHX", position: "F-G", number: "24", age: 38, height: "6'4\"", conf: "West", previousTeams: ["CON","IND"] },
  { id: 80025, name: "Alyssa Thomas", team: "PHX", position: "F", number: "25", age: 34, height: "6'2\"", conf: "West", previousTeams: ["CON"] },
  { id: 2054, name: "Jovana Nogic", team: "PHX", position: "G", number: "29", age: 28, height: "6'0\"", conf: "West", previousTeams: [] },
  { id: 2055, name: "Kyara Linskens", team: "PHX", position: "C", number: "31", age: 29, height: "6'4\"", conf: "West", previousTeams: [] },
  { id: 12033, name: "Sami Whitcomb", team: "PHX", position: "G", number: "33", age: 37, height: "5'10\"", conf: "West", previousTeams: ["SEA","NYL"] },
  { id: 2056, name: "Anneli Maley", team: "PHX", position: "F", number: "42", age: 27, height: "6'1\"", conf: "West", previousTeams: ["CHI"] },
  { id: 2057, name: "Marta Suarez", team: "PHX", position: "F", number: "77", age: 23, height: "6'3\"", conf: "West", previousTeams: [] },

  // POR — Fire
  { id: 5006, name: "Carla Leite", team: "POR", position: "G", number: "0", age: 22, height: "5'9\"", conf: "West", previousTeams: ["GSV"] },
  { id: 89, name: "Sug Sutton", team: "POR", position: "G", number: "1", age: 27, height: "5'8\"", conf: "West", previousTeams: ["PHX","WAS"] },
  { id: 73, name: "Sarah Ashlee Barker", team: "POR", position: "G", number: "3", age: 24, height: "6'0\"", conf: "West", previousTeams: ["LAS"] },
  { id: 15, name: "Bridget Carleton", team: "POR", position: "F", number: "6", age: 28, height: "6'2\"", conf: "West", previousTeams: ["CON","ATL","MIN"] },
  { id: 2058, name: "Teja Oblak", team: "POR", position: "G", number: "7", age: 35, height: "5'8\"", conf: "West", previousTeams: [] },
  { id: 2059, name: "Holly Winterburn", team: "POR", position: "G", number: "7", age: 26, height: "5'11\"", conf: "West", previousTeams: ["ATL"] },
  { id: 2060, name: "Kamiah Smalls", team: "POR", position: "G", number: "8", age: 28, height: "5'10\"", conf: "West", previousTeams: ["IND"] },
  { id: 2061, name: "Nyadiew Puoch", team: "POR", position: "F", number: "13", age: 21, height: "6'3\"", conf: "West", previousTeams: [] },
  { id: 137, name: "Luisa Geiselsoder", team: "POR", position: "C", number: "15", age: 26, height: "6'4\"", conf: "West", previousTeams: ["DAL"] },
  { id: 55, name: "Megan Gustafson", team: "POR", position: "C", number: "17", age: 29, height: "6'4\"", conf: "West", previousTeams: ["DAL","PHX","WAS","LVA"] },
  { id: 2062, name: "Frieda Buhner", team: "POR", position: "F-C", number: "20", age: 21, height: "6'2\"", conf: "West", previousTeams: [] },
  { id: 4421, name: "Emily Engstler", team: "POR", position: "F", number: "21", age: 26, height: "6'1\"", conf: "West", previousTeams: ["IND","MIN","WAS"] },
  { id: 2063, name: "Serah Williams", team: "POR", position: "F", number: "25", age: 23, height: "6'4\"", conf: "West", previousTeams: [] },
  { id: 5005, name: "Haley Jones", team: "POR", position: "F-G", number: "30", age: 24, height: "6'1\"", conf: "West", previousTeams: ["ATL","DAL"] },

  // SEA — Storm
  { id: 61, name: "Natisha Hiedeman", team: "SEA", position: "G", number: "2", age: 29, height: "5'8\"", conf: "West", previousTeams: ["CON","MIN"] },
  { id: 2064, name: "Flau'jae Johnson", team: "SEA", position: "G", number: "4", age: 22, height: "5'10\"", conf: "West", previousTeams: [] },
  { id: 87, name: "Jade Melbourne", team: "SEA", position: "G", number: "5", age: 23, height: "5'10\"", conf: "West", previousTeams: ["WAS"] },
  { id: 2065, name: "Zia Cooke", team: "SEA", position: "G", number: "7", age: 25, height: "5'9\"", conf: "West", previousTeams: ["LAS"] },
  { id: 50122, name: "Lexie Brown", team: "SEA", position: "G", number: "8", age: 31, height: "5'9\"", conf: "West", previousTeams: ["CON","MIN","CHI","LAS"] },
  { id: 2066, name: "Awa Fam", team: "SEA", position: "C", number: "11", age: 19, height: "6'4\"", conf: "West", previousTeams: [] },
  { id: 6006, name: "Ezi Magbegor", team: "SEA", position: "F-C", number: "13", age: 26, height: "6'6\"", conf: "West", previousTeams: [] },
  { id: 7007, name: "Dominique Malonga", team: "SEA", position: "C", number: "14", age: 20, height: "6'6\"", conf: "West", previousTeams: [] },
  { id: 2067, name: "Taina Mair", team: "SEA", position: "G", number: "22", age: 23, height: "5'9\"", conf: "West", previousTeams: [] },
  { id: 2068, name: "Jordan Horston", team: "SEA", position: "F", number: "23", age: 24, height: "6'2\"", conf: "West", previousTeams: [] },
  { id: 83, name: "Stefanie Dolson", team: "SEA", position: "C", number: "31", age: 34, height: "6'5\"", conf: "West", previousTeams: ["WAS","CHI","NYL"] },
  { id: 11033, name: "Katie Lou Samuelson", team: "SEA", position: "G", number: "33", age: 28, height: "6'3\"", conf: "West", previousTeams: ["CHI","DAL","LAS"] },
  { id: 2069, name: "Grace Vanslooten", team: "SEA", position: "F", number: "40", age: 22, height: "6'3\"", conf: "West", previousTeams: [] },
  { id: 2070, name: "Mackenzie Holmes", team: "SEA", position: "F", number: "54", age: 25, height: "6'3\"", conf: "West", previousTeams: [] },

  // TOR — Tempo
  { id: 2071, name: "Kiki Rice", team: "TOR", position: "G", number: "1", age: 22, height: "5'11\"", conf: "East", previousTeams: [] },
  { id: 2072, name: "Laura Juskaite", team: "TOR", position: "F", number: "2", age: 28, height: "6'4\"", conf: "East", previousTeams: [] },
  { id: 96, name: "Marina Mabrey", team: "TOR", position: "G", number: "3", age: 29, height: "6'1\"", conf: "East", previousTeams: ["LAS","DAL","CHI","CON"] },
  { id: 2073, name: "Teonni Key", team: "TOR", position: "F", number: "7", age: 22, height: "6'4\"", conf: "East", previousTeams: [] },
  { id: 144, name: "Nyara Sabally", team: "TOR", position: "F", number: "8", age: 26, height: "6'5\"", conf: "East", previousTeams: ["NYL"] },
  { id: 2074, name: "Maria Conde", team: "TOR", position: "F", number: "10", age: 29, height: "6'3\"", conf: "East", previousTeams: ["GSV"] },
  { id: 51, name: "Kia Nurse", team: "TOR", position: "G", number: "11", age: 30, height: "6'0\"", conf: "East", previousTeams: ["NYL","PHX","SEA","CHI"] },
  { id: 12012, name: "Lexi Held", team: "TOR", position: "G", number: "12", age: 26, height: "5'9\"", conf: "East", previousTeams: ["PHX"] },
  { id: 112, name: "Temi Fagbenle", team: "TOR", position: "C", number: "14", age: 33, height: "6'5\"", conf: "East", previousTeams: ["MIN","IND","GSV"] },
  { id: 20202, name: "Brittney Sykes", team: "TOR", position: "G", number: "20", age: 32, height: "5'11\"", conf: "East", previousTeams: ["ATL","LAS","WAS","SEA"] },
  { id: 21, name: "Isabelle Harrison", team: "TOR", position: "F", number: "21", age: 32, height: "6'5\"", conf: "East", previousTeams: ["PHX","LVA","DAL","CHI","NYL"] },
  { id: 41, name: "Julie Allemand", team: "TOR", position: "G", number: "22", age: 29, height: "5'10\"", conf: "East", previousTeams: ["IND","CHI","LAS"] },
  { id: 2075, name: "Nikolina Milic", team: "TOR", position: "C", number: "31", age: 32, height: "6'3\"", conf: "East", previousTeams: ["MIN"] },
  { id: 2076, name: "Mariella Fasoula", team: "TOR", position: "C", number: "34", age: 28, height: "6'4\"", conf: "East", previousTeams: [] },

  // WAS — Mystics
  { id: 75, name: "Shakira Austin", team: "WAS", position: "C", number: "0", age: 25, height: "6'5\"", conf: "East", previousTeams: [] },
  { id: 2077, name: "Alicia Florez Getino", team: "WAS", position: "G", number: "2", age: 27, height: "5'9\"", conf: "East", previousTeams: [] },
  { id: 2078, name: "Rori Harmon", team: "WAS", position: "G", number: "3", age: 22, height: "5'6\"", conf: "East", previousTeams: [] },
  { id: 2079, name: "Alex Wilson", team: "WAS", position: "G", number: "4", age: 31, height: "5'9\"", conf: "East", previousTeams: [] },
  { id: 2080, name: "Darianna Littlepage-Buggs", team: "WAS", position: "G-F", number: "5", age: 22, height: "6'1\"", conf: "East", previousTeams: [] },
  { id: 81, name: "Georgia Amoore", team: "WAS", position: "G", number: "8", age: 25, height: "5'6\"", conf: "East", previousTeams: [] },
  { id: 57, name: "Michaela Onyenwere", team: "WAS", position: "F", number: "12", age: 26, height: "6'0\"", conf: "East", previousTeams: ["NYL","PHX","CHI"] },
  { id: 2081, name: "Cassandre Prosper", team: "WAS", position: "G", number: "18", age: 21, height: "6'3\"", conf: "East", previousTeams: [] },
  { id: 82, name: "Sonia Citron", team: "WAS", position: "G", number: "22", age: 22, height: "6'1\"", conf: "East", previousTeams: [] },
  { id: 2082, name: "Cotie McMahon", team: "WAS", position: "G", number: "23", age: 22, height: "6'0\"", conf: "East", previousTeams: [] },
  { id: 2083, name: "Angela Dugalic", team: "WAS", position: "F", number: "32", age: 25, height: "6'4\"", conf: "East", previousTeams: [] },
  { id: 88, name: "Lucy Olsen", team: "WAS", position: "G", number: "33", age: 22, height: "5'10\"", conf: "East", previousTeams: [] },
  { id: 4944, name: "Kiki Iriafen", team: "WAS", position: "F", number: "44", age: 22, height: "6'3\"", conf: "East", previousTeams: [] },
  { id: 2084, name: "Lauren Betts", team: "WAS", position: "C", number: "51", age: 22, height: "6'7\"", conf: "East", previousTeams: [] },
];

export default players;
